version: '3'
services:
    mongodb:
        image: mongo
        container_name: kampan-mongodb
        volumes:
            - ../deployment/kampan/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
 
    web:
        build: .
        image: kampan-image
        container_name: kampan-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9800:9000
        links:
            - mongodb
        networks:
            - default
        restart: always
        environment:
            KAMPAN_SETTINGS: /app/kampan-production.cfg
        command:
            # uwsgi --lazy-apps --ini scripts/kampan-uwsgi.ini
            /venv/bin/gunicorn -w 2 --bind 0.0.0.0:9000 "kampan.web:create_app()"
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    redis:
        image: redis
        container_name: kampan-redis
        restart: always
        networks:
            - default
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    worker:
        build: .
        image: kampan-image
        container_name: kampan-worker
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - mongodb
            - redis
        links:
            - mongodb
            - redis
        restart: always
        environment:
            KAMPAN_SETTINGS: /app/kampan-production.cfg
        command:
            /venv/bin/kampan-worker
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    controller:
        build: .
        image: kampan-image
        container_name: kampan-controller
        volumes:
            # - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - mongodb
            - redis
        links:
            - mongodb
            - redis
        restart: always
        environment:
            KAMPAN_SETTINGS: /app/kampan-production.cfg
        command:
            /venv/bin/kampan-controller
        logging:
            options:
                max-size: "10m"
                max-file: "3"

networks:
    default:
